name: htmlwhitelist
version: 1.0.1-dev

description: >
  This library can be used to clean up html on the server.

  The main purpose is to convert html from an untrusted source
  to a version that's safe for rendering.

homepage: https://github.com/topdesk/dart-html-whitelist

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  html:  ^0.15.0

dev_dependencies:
  test: any
  lints: 1.0.1
