name: htmlwhitelist
version: 0.4.1

description: >
  This library can be used to clean up html on the server.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/topdesk/dart-html-whitelist
documentation:

environment:
  sdk: '>=1.8.3 <2.0.0'

dependencies:
  html:  '^0.13.1'

dev_dependencies:
  test: '^0.12.0'
