name: htmlwhitelist
version: 0.1.0

description: >
  This library can be used to clean up html.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/topdesk/dart-html-whitelist
documentation:

environment:
  sdk: '>=1.8.3 <2.0.0'

dependencies:
  html: any

dev_dependencies:
  test: '^0.12.0'
