name: htmlwhitelist
version: 0.5.2-dev

description: >
  This library can be used to clean up html on the server.

  The main purpose is to process html from an untrusted source
  and make sure that if the html is rendered by your
  application it doesn't contain elements that are not safe.

authors:
- Roel Spilker <r.spilker@gmail.com>

homepage: https://github.com/topdesk/dart-html-whitelist
documentation:

environment:
  sdk: '>=1.8.3 <2.0.0'

dependencies:
  html:  '^0.13.2+2'

dev_dependencies:
  test: '^0.12.30+1'
